targets:
- source: youtube_community
  target: '@ByteByteGo'
- source: rss
  target: https://news.ycombinator.com/rss
- source: reddit
  target: r/programming
- source: twitter
  target: '@ByteByteGo'
